
  version: "3.7"

  services:
    web:
      build: .
      container_name: letchat_web
      ports: 
        - "8000:8000"
      volumes: 
        - .:/app
      command: sh -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000" 
      environment: 
        - DEBUG=1
      depends_on:
        - redis
      links:
        - redis
    redis:
      image: redis
      container_name: letchat_redis
      volumes:
        - redis_data:/data
      ports:
        - "6379:6379"
  volumes:  
    redis_data:


